name: CD-Workflow

on:
  push:
    branches:
      - main 
jobs:
  cd-deploy-to-test:
    name: Deploy to test
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: install databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Install-Dependencies
        run: python -m pip install --upgrade pip
      - name: install hatch 
        run: pip install hatch
      - name: Build-hatch-wheel
        run: hatch build -t wheel
      - name: Configure Databricks 
        run: |
          cat <<EOF > ~/.databrickscfg
          host = https://adb-7405607648433478.18.azuredatabricks.net
          azure_client_id = ${{secrets.AZURE_CLIENT_ID}}
          azure_tenant_id = ${{secrets.AZURE_TENANT_ID}}
          azure_client_secret = ${{secrets.AZURE_CLIENT_SECRET}}
          EOF
      - name: Deploy to test
        run: databricks bundle deploy --target test --profile TEST
  cd-deploy-to-prod:
    name: Deploy to prod
    needs: cd-deploy-to-test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: install databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Install-Dependencies
        run: python -m pip install --upgrade pip
      - name: install hatch 
        run: pip install hatch
      - name: Build-hatch-wheel
        run: hatch build -t wheel
      - name: Configure Databricks 
        run: |
          cat <<EOF > ~/.databrickscfg
          host = https://adb-7405607648433478.18.azuredatabricks.net
          azure_client_id = ${{secrets.AZURE_CLIENT_ID}}
          azure_tenant_id = ${{secrets.AZURE_TENANT_ID}}
          azure_client_secret = ${{secrets.AZURE_CLIENT_SECRET}}
          EOF
      - name: Deploy to test
        run: databricks bundle deploy --target prod --profile PROD
        
